### ISSUE TITLE
Still under development?

### ISSUE THREAD

**Issue by jwhendy** [spob/openmind#2]
I'd love to use this for brainstorming at work! I'm not familiar with ruby/rails, and so I'm running into version problems I think because ruby has been updated a bunch since this was last revised.

For example:
- I have taskjuggler3 installed, which uses current ruby/rails versions
- I got to `rake gems:install` and get conflicts between 2.3.5 versions of gems and the rails3 versions
- thinking sphinx also wants > 3.0.3 for some gems, but the manual specifies installing rails 2.3.5

How does one get this up and running with current ruby/rails?

Are you developing this anymore? It's an awesome application and I really hope to use it!

**Comment by spob** [comment]
Hi John,

I'm sorry I took so long to reply to your email. And no, I'm sorry I'm not developing it anymore. While I love Rails, my day job doesn't afford me the opportunity to code in it, and I'm afraid I'm getting a bit rusty.  

My only suggestion would be to potentially reach out to some of the folks in github who have forked the repository. Perhaps some of them have taken it forward.

Good luck.

Bob

**Comment by jwhendy** [comment]
Thanks for the response. Bummer on that. It's a fantastic program, just can't get it going with my limited knowledge of Ruby/rails and how to get older versions installed. Seems like Sphinx is just not playing well with 2.3.5. I thought of checking the forks as well, but they seem like they haven't been updated in a long time either.  

Anyway, thanks for putting work into this -- I think it's a one of a kind program that has a ton of value! If work ever lets you dig back in... I'll be ready to try it out!

**Comment by spob** [comment]
Thanks for the kind words. I will keep you in mind.  

Cheers,

Bob
